[project]
name = "ctf"
version = "0.1.0"
description = "CTF Environment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "impacket>=0.13.0.dev0",
    "netexec",
    "pwntools>=4.14.0",
]

[tool.uv.sources]
netexec = { git = "https://github.com/Pennyw0rth/NetExec" }
